function out = ComputeTransmittanceToTopAtmosphereBoundary(...
    atmosphere, r, mu) 
  out = exp(-(...
      atmosphere.rayleigh_scattering .*...
          ComputeOpticalLengthToTopAtmosphereBoundary(...
              atmosphere, atmosphere.rayleigh_density, r, mu) +...
      atmosphere.mie_extinction .*...
          ComputeOpticalLengthToTopAtmosphereBoundary(...
              atmosphere, atmosphere.mie_density, r, mu)));
end