function out = GetTransmittanceToTopAtmosphereBoundary(...
    atmosphere,...
    transmittance_texture,...
    r, mu) 
  %assert(r >= atmosphere.bottom_radius && r <= atmosphere.top_radius);
  [u_r, u_mu] = RMuEncoding(atmosphere, r, mu);
  out = transmittance_texture(u_r, u_mu);
end